### ISSUE TITLE
Error installing paperspace-python on Windows 10

### ISSUE THREAD

**Issue by allanwright** [Paperspace/paperspace-python#16]
I am unable to successfully perform a pip install of paperspace-python on a machine with the following configuration:

OS: Windows 10 Pro x64
Anaconda: 4.3.1
Python: 3.6.0
Pip: 18.1 (updated after first install attempt failed)

See below for the output of the pip install.  I apologise in advance if this is not a real issue but I am not sure what else to try before logging this issue, apart from a pip upgrade and conda install of the paperspace api, which also fails.

```
Collecting paperspace
  Using cached https://files.pythonhosted.org/packages/71/8a/a8d5fdd72ab0c39760aa5f4f56d324dfd015b2b3ac30c0006ae818e35acf/paperspace-0.0.13.tar.gz
Requirement already satisfied: requests[security] in c:\users\allan\anaconda3\lib\site-packages (from paperspace) (2.12.4)
Requirement already satisfied: boto3 in c:\users\allan\anaconda3\lib\site-packages (from paperspace) (1.9.69)
Requirement already satisfied: botocore in c:\users\allan\anaconda3\lib\site-packages (from paperspace) (1.12.69)
Requirement already satisfied: six in c:\users\allan\anaconda3\lib\site-packages (from paperspace) (1.10.0)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\allan\anaconda3\lib\site-packages (from requests[security]->paperspace) (16.2.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\allan\anaconda3\lib\site-packages (from requests[security]->paperspace) (1.7.1)
Requirement already satisfied: idna>=2.0.0 in c:\users\allan\anaconda3\lib\site-packages (from requests[security]->paperspace) (2.2)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in c:\users\allan\anaconda3\lib\site-packages (from boto3->paperspace) (0.1.13)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\allan\anaconda3\lib\site-packages (from boto3->paperspace) (0.9.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in c:\users\allan\anaconda3\lib\site-packages (from botocore->paperspace) (2.6.0)
Requirement already satisfied: docutils>=0.10 in c:\users\allan\anaconda3\lib\site-packages (from botocore->paperspace) (0.13.1)
Requirement already satisfied: urllib3<1.25,>=1.20; python_version >= "3.4" in c:\users\allan\anaconda3\lib\site-packages (from botocore->paperspace) (1.24.1)
Requirement already satisfied: pyasn1>=0.1.8 in c:\users\allan\anaconda3\lib\site-packages (from cryptography>=1.3.4->requests[security]->paperspace) (0.1.9)
Requirement already satisfied: setuptools>=11.3 in c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg (from cryptography>=1.3.4->requests[security]->paperspace) (27.2.0)
Requirement already satisfied: cffi>=1.4.1 in c:\users\allan\anaconda3\lib\site-packages (from cryptography>=1.3.4->requests[security]->paperspace) (1.9.1)
Requirement already satisfied: pycparser in c:\users\allan\anaconda3\lib\site-packages (from cffi>=1.4.1->cryptography>=1.3.4->requests[security]->paperspace) (2.17)
Building wheels for collected packages: paperspace
  Running setup.py bdist_wheel for paperspace ... error
  Complete output from command c:\users\allan\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\allan\\AppData\\Local\\Temp\\pip-install-dsnu0m0c\\paperspace\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\allan\AppData\Local\Temp\pip-wheel-v13fd3og --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\paperspace
  copying paperspace\config.py -> build\lib\paperspace
  copying paperspace\jobs.py -> build\lib\paperspace
  copying paperspace\login.py -> build\lib\paperspace
  copying paperspace\machines.py -> build\lib\paperspace
  copying paperspace\main.py -> build\lib\paperspace
  copying paperspace\method.py -> build\lib\paperspace
  copying paperspace\networks.py -> build\lib\paperspace
  copying paperspace\scripts.py -> build\lib\paperspace
  copying paperspace\templates.py -> build\lib\paperspace
  copying paperspace\users.py -> build\lib\paperspace
  copying paperspace\__init__.py -> build\lib\paperspace
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\paperspace
  copying build\lib\paperspace\config.py -> build\bdist.win-amd64\wheel\.\paperspace
  copying build\lib\paperspace\jobs.py -> build\bdist.win-amd64\wheel\.\paperspace
  copying build\lib\paperspace\login.py -> build\bdist.win-amd64\wheel\.\paperspace
  copying build\lib\paperspace\machines.py -> build\bdist.win-amd64\wheel\.\paperspace
  copying build\lib\paperspace\main.py -> build\bdist.win-amd64\wheel\.\paperspace
  copying build\lib\paperspace\method.py -> build\bdist.win-amd64\wheel\.\paperspace
  copying build\lib\paperspace\networks.py -> build\bdist.win-amd64\wheel\.\paperspace
  copying build\lib\paperspace\scripts.py -> build\bdist.win-amd64\wheel\.\paperspace
  copying build\lib\paperspace\templates.py -> build\bdist.win-amd64\wheel\.\paperspace
  copying build\lib\paperspace\users.py -> build\bdist.win-amd64\wheel\.\paperspace
  copying build\lib\paperspace\__init__.py -> build\bdist.win-amd64\wheel\.\paperspace
  running install_egg_info
  running egg_info
  writing paperspace.egg-info\PKG-INFO
  writing dependency_links to paperspace.egg-info\dependency_links.txt
  writing entry points to paperspace.egg-info\entry_points.txt
  writing requirements to paperspace.egg-info\requires.txt
  writing top-level names to paperspace.egg-info\top_level.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'paperspace.egg-info\SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\allan\AppData\Local\Temp\pip-install-dsnu0m0c\paperspace\setup.py", line 37, in <module>
      'paperspace-python = paperspace.main:main',
    File "c:\users\allan\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\allan\anaconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\users\allan\anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\allan\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "c:\users\allan\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\allan\anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\install.py", line 61, in run
    File "c:\users\allan\anaconda3\lib\distutils\command\install.py", line 557, in run
      self.run_command(cmd_name)
    File "c:\users\allan\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\allan\anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\install_egg_info.py", line 35, in run
    File "c:\users\allan\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\allan\anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 195, in run
    File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 222, in find_sources
    File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 306, in run
    File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 342, in add_defaults
    File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\sdist.py", line 234, in read_manifest
    File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 247, in append
    File "c:\users\allan\anaconda3\lib\distutils\util.py", line 125, in convert_path
      raise ValueError("path '%s' cannot be absolute" % pathname)
  ValueError: path '/home/paperspace/paperspace-python/paperspace.egg-info/PKG-INFO' cannot be absolute

  ----------------------------------------
  Failed building wheel for paperspace
  Running setup.py clean for paperspace
Failed to build paperspace
Installing collected packages: paperspace
  Running setup.py install for paperspace ... error
    Complete output from command c:\users\allan\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\allan\\AppData\\Local\\Temp\\pip-install-dsnu0m0c\\paperspace\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\allan\AppData\Local\Temp\pip-record-86acwht8\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\paperspace
    copying paperspace\config.py -> build\lib\paperspace
    copying paperspace\jobs.py -> build\lib\paperspace
    copying paperspace\login.py -> build\lib\paperspace
    copying paperspace\machines.py -> build\lib\paperspace
    copying paperspace\main.py -> build\lib\paperspace
    copying paperspace\method.py -> build\lib\paperspace
    copying paperspace\networks.py -> build\lib\paperspace
    copying paperspace\scripts.py -> build\lib\paperspace
    copying paperspace\templates.py -> build\lib\paperspace
    copying paperspace\users.py -> build\lib\paperspace
    copying paperspace\__init__.py -> build\lib\paperspace
    running install_lib
    running install_egg_info
    running egg_info
    writing paperspace.egg-info\PKG-INFO
    writing dependency_links to paperspace.egg-info\dependency_links.txt
    writing entry points to paperspace.egg-info\entry_points.txt
    writing requirements to paperspace.egg-info\requires.txt
    writing top-level names to paperspace.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'paperspace.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\allan\AppData\Local\Temp\pip-install-dsnu0m0c\paperspace\setup.py", line 37, in <module>
        'paperspace-python = paperspace.main:main',
      File "c:\users\allan\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\allan\anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\allan\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\install.py", line 61, in run
      File "c:\users\allan\anaconda3\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "c:\users\allan\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\allan\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\install_egg_info.py", line 35, in run
      File "c:\users\allan\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\allan\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 195, in run
      File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 222, in find_sources
      File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 306, in run
      File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 342, in add_defaults
      File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\sdist.py", line 234, in read_manifest
      File "c:\users\allan\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\egg_info.py", line 247, in append
      File "c:\users\allan\anaconda3\lib\distutils\util.py", line 125, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/home/paperspace/paperspace-python/paperspace.egg-info/PKG-INFO' cannot be absolute

    ----------------------------------------
Command "c:\users\allan\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\allan\\AppData\\Local\\Temp\\pip-install-dsnu0m0c\\paperspace\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\allan\AppData\Local\Temp\pip-record-86acwht8\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\allan\AppData\Local\Temp\pip-install-dsnu0m0c\paperspace\
```

**Comment by Denton24646** [comment]
@ldelossa

**Comment by Denton24646** [comment]
Hey @allanwright maybe try deleting the file and trying again?

**Comment by allanwright** [comment]
I've found a workaround that allows me to successfully install the package.  It appears that SOURCES.txt contains an absolute path which pip doesn't like.

1.  Download https://files.pythonhosted.org/packages/71/8a/a8d5fdd72ab0c39760aa5f4f56d324dfd015b2b3ac30c0006ae818e35acf/paperspace-0.0.13.tar.gz and extract the contents to a directory on the machine you wish to install on.
2.  Delete paperspace-0.0.13/paperspace.egg-info/SOURCES.txt.
3.  Run 'pip install {path_to_locally_extracted_paperspace-0.0.13}'.

**Comment by BartoszCki** [comment]
Hi there @allanwright  Can you confirm that this issue has been resolved?

**Comment by allanwright** [comment]
Hi @BartoszCki, I can confirm that I am now able to install successfully.  Thanks for looking into this!

**Comment by BartoszCki** [comment]
@allanwright Thanks!
