### ISSUE TITLE
NameError: name 'time' is not defined

### ISSUE THREAD

**Issue by gcoter** [Paperspace/paperspace-python#33]
When running this command:

```
paperspace-python run --workspace Dockerfile --useDockerfile True -m unittest discover musicgeneration/tests/
```

I get the following error:

```
Traceback (most recent call last):
  File "/home/gcoter/projects/music/audio-music-generation/venv/bin/paperspace-python", line 10, in <module>
    sys.exit(main())
  File "/home/gcoter/projects/music/audio-music-generation/venv/lib/python3.6/site-packages/paperspace/main.py", line 112, in main
    res = run(params)
  File "/home/gcoter/projects/music/audio-music-generation/venv/lib/python3.6/site-packages/paperspace/jobs.py", line 418, in run
    res = create(params, no_logging)
  File "/home/gcoter/projects/music/audio-music-generation/venv/lib/python3.6/site-packages/paperspace/jobs.py", line 159, in create
    job = waitfor({'jobId': jobId, 'state': 'Running'})
  File "/home/gcoter/projects/music/audio-music-generation/venv/lib/python3.6/site-packages/paperspace/jobs.py", line 139, in waitfor
    time.sleep(5)
NameError: name 'time' is not defined
```

I think the problem is simply that the `time` module is not currently imported in `paperspace/jobs.py`.

I am using `paperspace-python 0.0.16` installed from pip.

**Comment by BartoszCki** [comment]
Thanks for pointing it out
This issue is fixed in release 0.0.19a0 - it's an alpha version of experiments support but creating jobs wasn't affected by this change and should be safe to use.

To install 0.0.19a0 (or any latest version including alphas and betas) use one of:
pip install paperspace --pre
pipenv install paperspace --pre
conda install paperspace
