### ISSUE TITLE
Cannot install paperspace

### ISSUE THREAD

**Issue by Overdrivr** [Paperspace/paperspace-python#34]
Running `pip install pipenv`:

```
Looking in indexes: https://pypi.python.org/simple, https://pypi.fury.io/cronobo
Collecting paperspace
  Using cached https://files.pythonhosted.org/packages/92/c7/72d0651c80c7404eed44fe4f51d3597867a2a6ccec2c818b097778352053/paperspace-0.0.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\remib\AppData\Local\Temp\pip-install-th_kznou\paperspace\setup.py", line 6, in <module>
        from paperspace.__version__ import version
      File "C:\Users\remib\AppData\Local\Temp\pip-install-th_kznou\paperspace\paperspace\__init__.py", line 1, in <module>
        from gradient_statsd import Client as StatsdClient
    ModuleNotFoundError: No module named 'gradient_statsd'

    ----------------------------------------

Error:  An error occurred while installing paperspace!
Command "python setup.py egg_info" failed with error code 1 in C:\Users\remib\AppData\Local\Temp\pip-install-th_kznou\paperspace\
You are using pip version 18.0, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

This is likely caused by a bug in paperspace. Report this to its maintainers.
```

It looks like some dependencies are missing. Installing manually `gradient_statsd` solves it, but then `boto3` package is claimed missing.

**Comment by BartoszCki** [comment]
@Overdrivr
